### ISSUE TITLE
Could add icons for these applications ? please

### ISSUE THREAD

**Issue by ghost** [gusbemacbe/suru-plus-aspromauros#1]
Could add icons for these applications ? please
org.deepin.flatdeb.deepin-image-viewer
org.deepin.flatdeb.deepin-screenshot
deepin repair
com.deepin.ScreenRecorder
org.deepin.flatdeb.deepin-voice-recorder
org.deepin.flatdeb.deepin-music
deepin calculator
deepin-launcher

**Comment by gusbemacbe** [comment]
Hello @chemel9 

**ENGLISH**

Sorry for my absence, I was working a lot with the alpha version of Suru++ for a week.

I will add all them later after finalising the version of Suru++. They are added to my to-do. 

I'm working with the alpha version of Suru++ (https://github.com/gusbemacbe/suru-plus-alpha), which goals are to get rid of all bugs, make it compatible with KDE and with more than 20 distributions, after Suru++ Asprómauros has worked successively in all distributions. I integrated Suru++ Asprómauros with the alpha version of Suru++.

**ESPAÑOL**

Perdón por mi ausencia. Estuve trabajando mucho con la versión alfa de Suru++ durante una semana.

Los agregaré más tarde después de finalizar la versión de Suru++. Fueron agregados a mi lista de tareas.

Estoy trabajando con la versión alfa de Suru++ (https://github.com/gusbemacbe/suru-plus-alpha), cuyos objetivos son deshacerse de todos los errores, hacerlo compatible con KDE y con más de 20 distribuciones, después de Suru++ Asprómauros haber trabajado sucesivamente en todas las distribuciones. Integré Suru++ Asprómauros con la versión alfa de Suru++.

**PORTUGUÊS**

Desculpe-me pela minha ausência, eu estava a trabalhar muito com a versão alfa de Suru++, passando uma semana. Foram adicionados à minha lista de tarefas. 

Adicioná-los-ei mais tarde após finalizar a versão de Suru++.

Estou a trabalhar com a versão alfa de Suru++ (https://github.com/gusbemacbe/suru-plus-alpha), cujos objectivos são livrá-lo de todos os bugs, torná-lo compatível com o KDE e com mais que 20 distribuições, após Suru++ Asprómauros ter funcionado successivamente em todas as distribuições. Integrei o Suru++ Asprómauros à versão alfa de Suru++.

**Comment by kurokirasama** [comment]
a jdownloader icon would be great too!

**Comment by naraesk** [comment]
Thanks for this awesome icon theme!

Had some small issues using it with KDE. Is is worth reporting or are you already aware of this issues? For example, when connecting an external monitor a plasma windows appears for choosing the external monitor configuration. Unfortunately, all icons are missing. I was wondering if it would help adding a kde icon theme (breeze) to the inheritance list?

**Comment by gusbemacbe** [comment]
@chemel9 and @kurokirasama 

The icons `deepin-calculator` and `jdownloader` are already present before. Maybe desktop configuration files of these two applications use the absolute path and the file extension, preventing the icons themes from applying the new icons. Please go to `/usr/share/applications`, go to these two applications and open them with Text Editor and find `Icon=...`, copy and paste there. 

@naraesk 

Strange, I made Asprómauros compatible with KDE and tested it on more than 20 distributions before releasing it. Maybe because of the issue #2 reported by @RollingTaters. 

I found `Inherits=...` unnecessary and removed it from `index.theme`. But, if you suggest, I will bring it back. 

I will release in ones hours and call you.

**Comment by naraesk** [comment]
If you say it is unnecessary it probably is. :-)

Found the icons that are missing: https://github.com/KDE/breeze-icons/tree/master/icons/applets/64
- osd-duplicate.svg
- osd-sbs-left.svg
- osd-sbs-sright.svg
- osd-shutd-laptop.svg
- osd-shutd-screen.svg

**Comment by gusbemacbe** [comment]
@naraesk 

Ah, the original author of old version of Suru++ did not create that, thank you for reporting the missed folder `applets`. I download this icons theme Breeze and I will add it to the next release of Suru++ Asprómauros and the alpha version of Suru++. 

@chemel9, I have just added some icons and released the new version, but I need the correct name of icon as I trained the tutorial to you.

**Comment by moorob** [comment]
Looking for Remarkable markdown editor icon please.  Love this icon set.

**Comment by gusbemacbe** [comment]
@moorob 

HI, my current version [Suru++ 20](/gusbemacbe/suru-plus) has Remarkable, but in the moment I am developing the [unstable branch](/gusbemacbe/suru-plus/tree/unstable-2). Once I finish the version, I will merge into this repository.

**Comment by gusbemacbe** [comment]
@chemel9, @kurokirasama, @naraesk and @moorob !

I inform you that I have upgraded Suru++ Asprómauros from the complete and bug-free Suru++ 25. Suru++ Asprómauros is already totally complete now. 

I hope it do not be complete for you.

Hey, it supports gradient colours and is compatible with Oomox. Yoy can change the solid colour of all 16px icons or the gradient colours of 16px apps, devices, mimetypes and places.
