### ISSUE TITLE
Need mimetype/48 in index.theme

### ISSUE THREAD

**Issue by Saryniah** [gusbemacbe/suru-plus-aspromauros#2]
(leafpad:13210): Gtk-WARNING **: 08:19:37.852: Theme directory mimetypes/48 of theme suru-plus-aspromauros has no size
Kept getting a GTK warning when opening leafpad. This fixed it, cheers

[mimetypes/48]
Size=48
Type=Fixed

**Comment by gusbemacbe** [comment]
Hi, thank you for reporting this problem. I will fix tomorrow. I have just arrived from the hspital.

**Comment by gusbemacbe** [comment]
@RollingTaters 

I have just fixed it and released the new version.

I credited you in the CHANGELOG. Thank you!
