### ISSUE TITLE
I do not see updates icon

### ISSUE THREAD

**Issue by DivaDevSoft** [gusbemacbe/suru-plus-aspromauros#3]
**ESPAÑOL**
Cuando el sistema tiene actualizaciones, el icono de actualización no aparece. Tengo instalado el pack de iconos Suru++ Asprómauros.
![icono_actualizacion_3](https://user-images.githubusercontent.com/45685894/49641980-18f70f80-fa12-11e8-9c60-9cf0d84de7a5.png)
Con el pack de iconos Breeze o Breeze-Dark el icono de actualización se ve perfectamente.
Muchas gracias por este impresionante  tema de iconos!!!

**ENGLISH**
When the system has updates, the update icon does not appear. I have installed the icon package Suru ++ Asprómauros.
With the Breeze-Dark or Breeze-Dark icon pack, the update icon looks great.
Thank you very much for this awesome icon theme !!

**Comment by gusbemacbe** [comment]
Hola @divad77 !

Cuando yo termine mi facultad para formarme hoy, revisaré todos los temas de ícones el lunes.

**Comment by DivaDevSoft** [comment]
OK, muchas gracias, estaré atento a futuras actualizaciones.

**Comment by gusbemacbe** [comment]
Hola @divad77 !

He terminado de completar el tema de íconos [Suru++ 25](/gusbemacbe/suru-plus) y [Suru++ Dark](/gusbemacbe/suru-plus-dark). Ahora, he hecho upgrade de Suru++ Asprómauros a partir del Suru++ 25 Dark. 

Suru++ Asprómauros ya está totalmente completo ahora.

Espero que no esté completo para ti ahora.

Hey, también es compatible con colores degradados y es compatible con [Oomox](/actionless/oomox). Puedes cambiar el color sólido de todos los iconos de 16 píxeles o los colores degradados de íconos de `apps`, `devices`, `mimetypes` y `places` de 16 píxeles.
