### ISSUE TITLE
Could you add these icons please?

### ISSUE THREAD

**Issue by IvanDeFelice76** [gusbemacbe/suru-plus-aspromauros#8]
OphCrack
Devede
DVD95
Conky
OnionShare

**Comment by gusbemacbe** [comment]
Ciao @xzj8b3, ho fatto un _upgrade_ del tema di icone e queste icone sono state aggiunte, ma continuo a fare _upgrade_. Ho aggiunto il sopporto di gradienti per «apps/symbolic». Poi puoi caricare la versione beta.

**Comment by IvanDeFelice76** [comment]
> Ciao @ xzj8b3 , ho fatto un _aggiornamento_ del tema di icone e queste icone sono state aggiunte, ma continuo un _aggiornamento_ tariffa . Ho aggiunto il sopporto di gradienti per «app / simbolico». Poi puoi caricare la versione beta.

Excellent thanks a lot
