### ISSUE TITLE
No icon for Joplin - Note taking app

### ISSUE THREAD

**Issue by tylerelias** [gusbemacbe/suru-plus-aspromauros#9]
Hey,
First of all, I want to thank you for your hard work and these awesome icons.

Now I use this app called Joplin for note taking in University, and it's the only icon I found so far that isn't in this awesome icon theme, is there a possibility to have it added? 

Anyway, here is their repo:
https://github.com/laurent22/joplin

**Comment by gusbemacbe** [comment]
Hi @tylerelias !

I have the icons [appimagekit-joplin.svg](https://github.com/gusbemacbe/suru-plus-aspromauros/blob/master/Suru++-Aspr%C3%B3mauros/apps/16/appimagekit-joplin.svg) and [joplin.svg](https://github.com/gusbemacbe/suru-plus-aspromauros/blob/master/Suru++-Aspr%C3%B3mauros/apps/16/joplin.svg).

I will investigate another missed icon.

**Comment by gusbemacbe** [comment]
I have just investigated.

Did you install JOplin, using the command line, right? So it created an desktop file and it uses an AppImage. Here is its desktop file:

```
[Desktop Entry]
Encoding=UTF-8
Name=Joplin
Comment=Joplin for Desktop
Exec=/home/gusbemacbe/.joplin/Joplin.AppImage
Icon=/home/gusbemacbe/.joplin/Icon512.png
StartupWMClass=Joplin
Type=Application
Categories=Application;
X-AppImage-BuildId=1LpSDS79QxkAP8oaIYEmKvLumiN
```

You can see as the `Icon=/home/gusbemacbe/.joplin/Icon512.png` is hardcoded. We have to change to softcoded path like:

```
Icon=joplin
```

The problem is that, as `X-AppImage-BuildId=1LpSDS79QxkAP8oaIYEmKvLumiN` is present, it will update the AppImage and reverts the icon path to the original.

**Comment by tylerelias** [comment]
Yeah I installed it from AUR repo. I'm a little surprised that they hardcode the icons like that. 

But thank you for looking into this for me, I guess I could head over to their repo and report this as an issue since this hinders customization for the user.

**Comment by gusbemacbe** [comment]
I also was going to suggest them. I think you should open a topic with them about the hardcoding and the softcoding.

**Comment by tylerelias** [comment]
I raised the issue here:
https://github.com/laurent22/joplin/issues/1611

I directed them to this issue since your second reply goes into very good detail about the problem and I'm not as familiar with what practices should be followed when it comes to softcoding icons.

**Comment by gusbemacbe** [comment]
Great, @tylerelias, let's see their answer and their decision. If they decide that their app do not be themed, I will prepare a quick and small tutorial you.

I saw you are on Arch Linux, I really intend to migrate from deceased Antergos to Arch Linux, following @freefreeno's guide, when I will be ready with this icons theme the which I am upgrading in the branch `beta`, at the moment.

**Comment by tylerelias** [comment]
Good to see this get resolved so quickly over on their issue ticket, and thank you for implementing the fix.

Yeah I was reading about Antergos being discontinued. Setting Arch up from scratch is a good learning process, but you encounter a lot of issues you had not thought about before, because you decide all packages that get installed into your system.
Being familiar with mounting in the terminal and creating your own GRUB for your system will make this process a lot easier. I have a dual boot for Windows 10 (for some Uni work) and that's what I was getting stuck on since I didn't know that you had to mount the W10 bootloader partition to the /boot/ dir on your arch system when generating a grub-mkconfig for GRUB. Or perhaps Antergos will just push some update that migrates its users to Arch automatically and save them a lot of time.

Anyway going off topic here. Since you have resolved this in the Joplin repo I will close this issue since it has been resolved!

**Comment by gusbemacbe** [comment]
> Or perhaps Antergos will just push some update that migrates its users to Arch automatically and save them a lot of time.

Antergos developers said in their article that they will update the pacman config to remove Antergos-related packages and will add Arch Linux pacman config. But I am not sure if it is good idea because of bootloader as @freefreeno has indicated.

I think it is better to make clean install. 

> Good to see this get resolved so quickly over on their issue ticket, and thank you for implementing the fix.
> Anyway going off topic here. Since you have resolved this in the Joplin repo I will close this issue since it has been resolved!

Yes, I hope the pull request be approved. If approved, update via command line via AUR.

**Comment by gusbemacbe** [comment]
Hi @tylerelias !

My pull request has been approved now. You can update the app now.

**Comment by gusbemacbe** [comment]
Take an advantage as a new version of Suru++ Asprómauros has been released today. Now it supports gradients for all the icons. I also updated Oomox.

**Comment by tylerelias** [comment]
Great news, thank you!
